apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring   # must match Helm release name
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - expensy
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
