apiVersion: apps/v1
kind: Deployment
metadata:
  name: pablo-backend
  namespace: expensy
  labels:
    app: backend
    owner: pablo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        owner: pablo
    spec:
      containers:
        - name: backend
          image: docker.io/prouan/expensy-backend:latest
          ports:
            - containerPort: 8706
          envFrom:
            - configMapRef:
                name: expensy-config
            - secretRef:
                name: expensy-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: expensy
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
    - name: http    # 👈 added port name
      port: 8706
      targetPort: 8706
  selector:
    app: backend
