apiVersion: apps/v1
kind: Deployment
metadata:
  name: pablo-frontend
  namespace: expensy
  labels:
    app: frontend
    owner: pablo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        owner: pablo
    spec:
      containers:
        - name: frontend
          image: docker.io/prouan/expensy-frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: expensy-config
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: expensy
  labels:
    app: frontend
    owner: pablo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: frontend