apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expensy-ingress
  namespace: expensy
  annotations:
    # Use the nginx Ingress controller.  Ensure an ingress controller is
    # installed on your AKS cluster (e.g. via `helm install nginx-ingress`).
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          # Route all requests beginning with /api to the backend service.
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 8706
          # Everything else goes to the frontend service.  This ensures the
          # web UI is served at the root of the domain.
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80