apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pablo-mongo
  namespace: expensy
spec:
  serviceName: pablo-mongo
  replicas: 1
  selector:
    matchLabels:
      app: pablo-mongo
  template:
    metadata:
      labels:
        app: pablo-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: expensy-secrets
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: expensy-secrets
              key: MONGO_INITDB_ROOT_PASSWORD
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: managed-premium   # <-- specify storage class
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pablo-mongo
  namespace: expensy
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: pablo-mongo
