apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
  namespace: expensy
  labels:
    app: expensy
    owner: pablo
type: Opaque
stringData:
  # Full MongoDB connection string used by the backend.  The service
  # name `pablo-mongo` will resolve to the StatefulSet pod’s DNS name.
  DATABASE_URI: "mongodb://root:example@pablo-mongo:27017/expensy?authSource=admin"
  # Password used by Redis.  The same value is passed into the
  # StatefulSet via the REDIS_PASSWORD environment variable.
  REDIS_PASSWORD: "someredispassword"
  # Credentials used to initialise the Mongo container on first start
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "example"