apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
  namespace: expensy
  labels:
    app: expensy
    owner: pablo
type: Opaque
stringData:
  DATABASE_URI: "mongodb://root:example@pablo-mongo:27017/expensy?authSource=admin"
  REDIS_PASSWORD: "someredispassword"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "example"