apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
  namespace: expensy
type: Opaque
stringData:
  mongo-uri: "mongodb://root:example@pablo-mongo:27017/expensy?authSource=admin"
  redis-password: "someredispassword"
